# Generated by Django 4.1.7 on 2023-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveCalculator', '0002_leave_leave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=264, unique=True),
        ),
    ]
