# Generated by Django 4.1.7 on 2023-03-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('misogynyDetector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='recording',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
